FROM nvcr.io/nvidia/pytorch:23.03-py3

RUN apt-get -y update \
        && apt-get install -y gdb 


RUN pip install ogb \
        && pip install rdkit 

ENV DGL_HOME=/workspace2/dgl
ENV DGL_LIBRARY_PATH=/workspace2/dgl/build
ENV PYTHONPATH="/workspace2/fuse_attention/package:/workspace2/fuse_attention:/workspace2/python_profiler:/workspace2/dgl/python:$PYTHONPATH"
